{
 "title": "Django Monitoring - by us",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uso de CPU del Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errores y respuestas exitosas (200, 404, 500)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peticiones por Vista, Método y Transporte",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "django_http_requests_total_by_view_transport_method_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de solicitudes HTTP (GET, POST, etc.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}