global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-42'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['auth-42:8442']
    metrics_path: /metrics/

  - job_name: 'auth-local'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['auth-local:8441']
    metrics_path: /metrics/
