global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-42:8000', 'auth-local:8001']
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
